name: Serverless Docker Push Image

permissions:
  id-token: write
  contents: read
  packages: write

on: 
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        default: '16'
        type: choice
        options:
          - 12
          - 16
          - 18
          - 20
      sls:
        description: 'Serverless version'
        required: false
        default: '3.39.0'

jobs:
  pushImage:
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run: |
        echo "Building image with serverless version: ${{ github.event.inputs.sls }} and node version ${{ github.event.inputs.node-version }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to image repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: sls-docker-image
        build-args: |
          "SLS_VERSION=${{ github.event.inputs.sls }}"
          "NODE_VERSION=${{ github.event.inputs.node-version }}"
        push: true
        tags: ghcr.io/exporo/sls-docker-image:v${{ github.event.inputs.node-version }}

